name: Build Debug APK

# 主分支提交代码时，构建调试版本 APK（不需要签名密钥）
on:
  push:
    branches:
      - master

jobs:
  package:
    name: Generate Debug APK
    runs-on: ubuntu-latest
    steps:
      # 1.拉取代码
      - name: checkout source code
        uses: actions/checkout@v3

      # 2.配置JDK
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # 3.授予 gradlew 执行权限
      - name: make gradlew executable
        run: chmod +x gradlew

      # 4.构建调试 APK
      - name: assemble debug apk
        run: ./gradlew clean assembleDebug --stacktrace

      # 5.查找并上传所有生成的 APK
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DanDanPlay-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 30
